# Bradford Smith
# Makefile for git-summary
# 07/29/2017
################################################################################

PREFIX ?= /usr/local
MANPREFIX ?= "$(PREFIX)/share/man/man1"

PRG = git-summary
MAN = man/git-summary.1
RM = rm -f

# include options generated by ./configure script
-include Makefile.in

.PHONY: all clean dry-run install uninstall

all:
	@echo "usage: make install"
	@echo "       make uninstall"
	@echo "       make dry-run"
	@echo "       make clean"

clean:
	$(RM) Makefile.in

dry-run:
	@echo "Running 'make install' would install $(PRG) to $(DESTDIR)$(PREFIX)/bin"
	@echo "        and $(MAN) to $(DESTDIR)$(MANPREFIX)"

install:
	install -Dm 0755 $(PRG) -t $(DESTDIR)$(PREFIX)/bin
	install -Dm 0644 $(MAN) -t $(DESTDIR)$(MANPREFIX)

uninstall:
	$(RM) $(DESTDIR)$(PREFIX)/bin/$(PRG)
	$(RM) $(DESTDIR)$(MANPREFIX)/$(MAN)
