# Bradford Smith
# Makefile for git-summary
# 07/27/2017
################################################################################

PREFIX=/usr/local

PRG=git-summary
RM=rm -f

# include options generated by ./configure script
-include Makefile.in

.PHONY: all clean dry-run install uninstall

all:
	@echo "usage: make install"
	@echo "       make uninstall"
	@echo "       make dry-run"
	@echo "       make clean"

clean:
	$(RM) Makefile.in

dry-run:
	@echo "Running 'make install' would install $(PRG) to $(DESTDIR)$(PREFIX)/bin"

install:
	install -Dm 0755 $(PRG) -t $(DESTDIR)$(PREFIX)/bin

uninstall:
	$(RM) $(DESTDIR)$(PREFIX)/bin/$(PRG)
